Source/eDCMS/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path('login/', views.mylogin, name='login'),
    path('', views.home, name='home'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('signup', views.signup, name='signup'),
    path('reset-password/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', views.profile, name='profile_page'),
    path('profile_update/', views.update_profile, name='profile_update'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
    path('ajax/load-department/', views.load_department, name='ajax_load_department'),
    path('home/dashboard/', views.DashboardView.as_view(), name='dashboard'),
]

Source/eDCMS/eDCMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('recordmgnts/', include('recordmgnts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('mailings/', include('mailings.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Source/eDCMS/recordmgnts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'recordmgnts'


urlpatterns = [
    path('records/', views.showContainer, name='records'),
    path('records/new_container', views.addContainer, name='new_container'),
    path('records/new_container/success_added', TemplateView.as_view(template_name="success_added.html"), name='success'),
    path('<int:id>/', views.ContainerDetailView.as_view(), name='container_view'),
    path('delete/<int:id>/', views.containerDelete, name='container_delete'),
    path('search/', views.SearchContainerView.as_view(), name='container_search'),
    path('records/edit_records/<int:pk>/', views.containerUpdate, name='edit_records'),
    path('transaction/', views.transaction_log, name='transaction_log'),
    path('load_document_series/', views.load_series_number, name='ajax_load_doc_number'),
    path('ajax/load-locations/', views.load_locations, name='ajax_load_locations'),
    path('ajax/load-containers/', views.load_containers, name='ajax_load_containers'),
    path('transaction/history/', views.transaction_history_view, name='order_transaction_history_view'),
    path('transaction/history/<int:id>/', views.transaction_form_view, name='order_transaction_details_view'),
]

Source/eDCMS/accounts/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractUser


# Create your models here.


class Profile(AbstractUser):
    class Meta:
        verbose_name_plural = 'Profiles'
    company                  = models.ForeignKey('generals.Company', on_delete=models.CASCADE)
    contact                  = models.CharField(max_length=35, null=True)
    branch                   = models.ForeignKey('generals.Branch', on_delete=models.CASCADE)
    department               = models.ForeignKey('generals.Department', on_delete=models.CASCADE, blank=True, null=True)
    created_by               = models.CharField(max_length=120)
    modify_by                = models.CharField(max_length=120)
    modify_date              = models.DateTimeField(auto_now=True, null=False)
    is_active                = models.BooleanField(default=False, null=True, blank=True)
    is_superuser             = models.BooleanField(default=False, null=True, blank=True)
    is_staff                 = models.BooleanField(default=False, null=True, blank=True)
    is_documentcontroller    = models.BooleanField(default=False, null=True, blank=True)
    supervisor               = models.ForeignKey('Profile', null=True, on_delete=models.SET_NULL, blank=True)
    email                    = models.CharField(max_length=70, null=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

Source/eDCMS/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .forms import UserRegistrationForm, PasswordResetForm, ChangePasswordForm, CustomUserChangeForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from accounts.models import Profile
from .models import Profile
from generals.models import Branch, Department
from pprint import pprint
import json
from django.db.models import Count, Q
from django.views import View
from django.http import JsonResponse
from django.views.generic import TemplateView
from recordmgnts.models import Container
from django.contrib.auth.mixins import LoginRequiredMixin


def mylogin(request):
    if request.user.is_authenticated:
        return redirect('accounts:home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active is None and user.is_superuser is None:
                messages.warning(request, f'Account is not activated')
            else:
                # correct username and password login the user
                login(request, user)
                return redirect('accounts:home')

        else:
            messages.warning(request, f'Incorrect username or password')

    return render(request, 'registration/login.html')


def signup(request):
    if request.user.is_authenticated:
        return redirect('accounts:home')

    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        email = form.data['email']
        email += "@huayang.com.my"
        username = str(form.data['first_name']) + " " + str(form.data['last_name'])
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.created_by = username
            new_form.modify_by = username
            new_form.email = email
            new_form.save()
            messages.success(request, f'Your account has been created')
            return redirect('accounts:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def load_department(request):
    branch_id = request.GET.get('branch')
    departments = Department.objects.filter(branch=branch_id)
    if request.user.is_authenticated:
        current_department = request.user.department
        return render(request, 'accounts/dept_dropdown_list.html', {'departments': departments, 'curr_dept': current_department})
    else:
        return render(request, 'accounts/dept_dropdown_list.html', {'departments': departments})


class MyPasswordResetView(auth_views.PasswordResetView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('accounts:home')
        return super(MyPasswordResetView, self).get(request, *args, **kwargs)


class MyPasswordConfirmView(auth_views.PasswordResetConfirmView):
    form_class = PasswordResetForm


class MyPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('accounts:home')
        return super(MyPasswordResetCompleteView, self).get(request, *args, **kwargs)


class MyPasswordChangeView(SuccessMessageMixin, auth_views.PasswordChangeView):
    form_class = ChangePasswordForm
    success_url = reverse_lazy('accounts:profile_page')

    def get_success_message(self, cleaned_data):
        return 'Your password has been changed successfully'


@login_required
def home(request):
    return render(request, 'accounts/home.html')


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


@login_required
def update_profile(request):
    email_name = request.user.email.split('@', 1)[0]
    initial_data = {
        'username': request.user.username,
        'contact': request.user.contact,
        'email': email_name,
        'department': request.user.department,
        'company': request.user.company,
        'branch': request.user.branch,
        'supervisor': request.user.supervisor,
        'is_superuser': request.user.is_superuser,
        'is_staff': request.user.is_staff,
        'is_documentcontroller': request.user.is_documentcontroller
    }
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        email = form.data['email']
        email += "@huayang.com.my"
        if form.is_valid():
            fs = form.save(commit=False)
            fs.email = email
            fs.modify_by = str(request.user)
            fs.save()
            messages.success(request, f'Your profile has been updated')
            return redirect('accounts:profile_page')

    else:
        form = CustomUserChangeForm(initial=initial_data)
    return render(request, 'accounts/profile_update_form.html', {'form': form})


# class dashboard_view(View):
#     template_name = 'accounts/dashboard.html'
class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/dashboard.html'

    def get_dept(self):
        dataset = Container.objects \
            .values('department') \
            .annotate(IT_count=Count('department', filter=Q(department='IT') & Q(is_deleted=False)),
                      Ceo_count=Count('department', filter=Q(department='CEO') & Q(is_deleted=False)),
                      Corp_comm_count=Count('department', filter=Q(department='Corp Comm') & Q(is_deleted=False)),
                      Management_count=Count('department', filter=Q(department='Management') & Q(is_deleted=False)),
                      Sales_marketing_count=Count('department', filter=Q(department='Sales & Marketing') & Q(is_deleted=False)),
                      Admin_count=Count('department', filter=Q(department='Admin') & Q(is_deleted=False)),
                      Project_count=Count('department', filter=Q(department='Project') & Q(status=False) & Q(is_deleted=False)),
                      Accounts_count=Count('department', filter=Q(department='Accounts & Finance') & Q(is_deleted=False)),
                      Sales_admin_count=Count('department', filter=Q(department='Sales Admin') & Q(is_deleted=False)),
                      HR_count=Count('department', filter=Q(department='HR') & Q(is_deleted=False))) \
            .order_by('department')

        categories = list()
        IT_series_data = list()
        Sales_marketing_series_data = list()
        Sales_admin_series_data = list()
        Ceo_series_data = list()
        Corp_comm_series_data = list()
        Management_series_data = list()
        Admin_series_data = list()
        Accounts_series_data = list()
        Project_series_data = list()
        HR_series_data = list()

        for entry in dataset:
            if entry['department'] == 'CEO':
                categories.append('CEO')
            else:
                categories.append('%s Department' % entry['department'])
            IT_series_data.append(entry['IT_count'])
            Sales_marketing_series_data.append(entry['Sales_marketing_count'])
            Admin_series_data.append(entry['Admin_count'])
            Sales_admin_series_data.append((entry['Sales_admin_count']))
            Accounts_series_data.append(entry['Accounts_count'])
            Ceo_series_data.append(entry['Ceo_count'])
            Corp_comm_series_data.append(entry['Corp_comm_count'])
            Management_series_data.append(entry['Management_count'])
            Project_series_data.append(entry['Project_count'])
            HR_series_data.append(entry['HR_count'])

        IT_series = {
            'name': 'IT',
            'data': IT_series_data,
            'color': 'green'
        }

        Sales_marketing_series = {
            'name': 'Sales & Marketing',
            'data': Sales_marketing_series_data,
            'color': 'yellow'
        }

        Sales_admin_series = {
            'name': 'Sales Admin',
            'data': Sales_admin_series_data,
            'color': 'purple'
        }

        Admin_series = {
            'name': 'Admin',
            'data': Admin_series_data,
            'color': 'red'
        }

        HR_series = {
            'name': 'HR',
            'data': HR_series_data,
            'color': 'blue'
        }

        Accounts_series = {
            'name': 'Accounts & Finance',
            'data': Accounts_series_data,
            'color': 'black'
        }

        Ceo_series = {
            'name': 'CEO',
            'data': Ceo_series_data,
            'color': 'grey'
        }

        Corp_comm_series = {
            'name': 'Corp Comm',
            'data': Corp_comm_series_data,
            'color': 'pink'
        }

        Management_series = {
            'name': 'Management',
            'data': Management_series_data,
            'color': 'brown'
        }

        Project_series = {
            'name': 'Project',
            'data': Project_series_data,
            'color': 'orange'
        }

        chart2 = {
            'chart': {
                'type': 'column',
                'backgroundColor': '#E3F0E6',
                'option3d': {
                    'enabled': "true",
                    'alpha': 10,
                    'beta': 15,
                    'depth': 50,
                }
            },
            'title': {'text': 'Containers per Department'},
            'xAxis': {'categories': categories},
            'yAxis': {
                'title': {
                    'text': 'No.of containers'},
                'tickInterval': 1
            },
            'plotOptions': {
                'column': {
                    'stacking': 'normal',

Source/eDCMS/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.rawgit.com/serratus/quaggaJS/0420d5e0/dist/quagga.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />

    <title>{% block title %}eDCMS{% endblock title %}</title>
</head>

<body style='background:url("/static/accounts/background.png")'>

<div class="container-fluid" id="page-container">
   <header id="nav-bar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% if user.is_authenticated %}
        <div class="toggle-btn" onclick="toggleSidebar()">
            <i class="fa fa-bars"></i>
        </div>
        <div class="navbar-brand" href="{% url 'accounts:home' %}"><img src="{% static 'accounts/huayanglogo.png' %}"></div>
        {% else %}
        <div class="navbar-brand" style="margin-left:-50px"><img src="{% static 'accounts/huayanglogo.png' %}"></div>
        {% endif %}
        {% if user.is_authenticated %}
        <button style="margin:5px 10px" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:profile_page' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
            </li>
          </ul>
        </div>
        {% endif %}
    </nav>
   </header>


    <div id="sidebar">
        <ul class="list-unstyled components">
            <li><a href="{% url 'accounts:dashboard' %}" onclick="toggleSidebar()">Dashboard</a></li>
            <!--list with dropdown-->
            <li>
                <a href="#docSubMenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Document Management</a>
                <ul class="collapse list-unstyled" id="docSubMenu">
                    <li>
                        <a href="{% url 'recordmgnts:records' %}" onclick="toggleSidebar()">View</a>
                    </li>
                    <li>
                        <a href="{% url 'recordmgnts:transaction_log' %}" onclick="toggleSidebar()">Make A Transaction</a>
                    </li>
                    <li>
                        <a href="{% url 'recordmgnts:order_transaction_history_view' %}" onclick="toggleSidebar()">My Transactions</a>
                    </li>
                </ul>
            </li>
            <!--end list with dropdown-->
<!--            <li><a href="#" onclick="toggleSidebar()">Mailings</a></li>-->
<!--                <li><a href="#" data-toggle="popover" data-trigger="focus" data-content="Currently unavailable">Mailings</a></li>-->
           {% if user.is_superuser %}
            <li><a href="/admin" onclick="toggleSidebar()">Admin Site</a></li>
            {% endif %}
        </ul>
    </div>

    <div id="overlay" onclick="off()"></div>


    <div id="content-wrap">
   {% block content %}{% endblock %}
    </div>

   <div id="footer">
        <div class="container">
                <div class="col" style="margin-top:15px; text-align:center">
                    <a href="http://www.huayang.com.my/main/index.html"><i class="fa fa-google" style="font-size:35px;color:grey;"></i></a>&ensp;
                    <a href="https://www.youtube.com/channel/UCxej-a2H7o_BS5mYGA6Cdug"><i class="fa fa-youtube-play" style="font-size:35px;color:grey;"></i></a>&ensp;
                    <a href="https://www.facebook.com/huayangberhad"><i class="fa fa-facebook-square" style="font-size:35px;color:grey;"></i></a><br>
                </div>
            <p class="small" style="text-align:center">© Copyright 2018 Hua Yang Berhad. All Rights Reserved.</p>
        </div>
    </div>
</div>
<script>
    function toggleSidebar(){
        document.getElementById("sidebar").classList.toggle('active');
        document.getElementById("overlay").classList.toggle('active');
    }

    function off(){
        document.getElementById("sidebar").classList.toggle('active');
        document.getElementById("overlay").classList.toggle('active');
    }

    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
</script>
</body>
</html>

Source/eDCMS/accounts/templates/accounts/dept_dropdown_list.html
<option value="">---------</option>
{% if curr_dept %}
{% for department in departments %}
{% if department == curr_dept %}
<option value="{{ department.id }}" selected>{{ department.department }}</option>
{% elif department != curr_dept %}
<option value="{{ department.id }}">{{ department.department }}</option>
{% endif %}
{% endfor %}

{% else %}
{% for department in departments %}
<option value="{{ department.id }}">{{ department.department }}</option>
{% endfor %}
{% endif %}

Source/eDCMS/accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}
{% block title %} eDCMS-Home {% endblock title %}
{% block content %}
   <!------------banner section-------------->

   <!----Services section----->
   <section id="services">
       <div class="container text-center jumbotron col-md-8 col-sm-6 ">
            <h1>Welcome, {{ user.username }}!</h1>
       </div>
   </section>
{% endblock content %}

Source/eDCMS/accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% block title %}Password reset {% endblock title %}

{% block content %}
<div class="container" style="margin-left:50px; margin-top:30px">
    <h2 style="margin-bottom:40px">Password reset sent.</h2>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered.
        You should receive them shortly.
    </p>
    <p>
        If you don't receive an email, please make sure you've entered the address you registered with,
        and check your spam folder.
    </p>
</div>
{% endblock %}

Source/eDCMS/accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% block title %} eDCMS-{{ user.username }}{% endblock title %}
{% block content %}
<div class="content-section" style="margin-top:80px">
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="jumbotron container-fluid">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible text-center col-md-5" style="margin:0 auto" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <small class="text-muted">{{ message }}</small>
        </div>
        {% endfor %}
        {% endif %}
                <div class="dropdown show">
                    <h1>{{ user.get_full_name }}
                    <a class="small dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:black">
                    </a>
                    <span class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'accounts:profile_update' %}"><i class="fa fa-edit"></i> Update profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:password_change' %}"><i class="fa fa-key"></i> Change password</a>
                    </span>
                    </h1>
                </div>
                <hr>
        <div class="row" id="display-text">
            <div class="col">
                <p><b>Username: </b>{{ user.username }}</p>
                <p><b>Company: </b>{{ user.company }}</p>
                <p><b>Branch: </b>{{ user.branch }}</p>
                <p><b>Department: </b>{{ user.department }}</p>
            </div>
            <div class="col">
                <p><b>Email: </b>{{ user.email }}</p>
                <p><b>Contact: </b>{{ user.contact }}</p>
				<p><b>Superior: </b>{% if user.supervisor is not None %}{{ user.supervisor }} {% else %} - {% endif %} </p>
            </div>
        </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

Source/eDCMS/accounts/templates/accounts/profile_update_form.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}
{% block title %}eDCMS-Update Profile{% endblock %}
{% load crispy_forms_tags %}
{% crispy form form.helper %}
{% block content %}
    <div class="content-section" style="margin-top:80px">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card jumbotron">
                    <div class="border-bottom mb-4"><h2 style="text-align:center">Update Profile</h2></div>
                    <article class="card-body">
                        {% crispy form %}
                    </article>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>

           $(document).ready(function(){
           var branchId = $("#id_branch").val();

           $.ajax({
           url: "{% url 'accounts:ajax_load_department' %}",
           data: {
           'branch': branchId
           },
           success: function (data) {
           $("#id_department").html(data);
           }
           });

           });

           $("#id_branch").change(function () {
           var branchId = $(this).val();

           $.ajax({
           url: "{% url 'accounts:ajax_load_department' %}",
           data: {
           'branch': branchId
           },
           success: function (data) {
           $("#id_department").html(data);
           }
           });

           });
    </script>
{% endblock %}

Source/eDCMS/accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% block title %} Sign up {% endblock title %}
{% load crispy_forms_tags %}
{% crispy form form.helper %}
{% block content %}

<style>
    .input-group.is-invalid {
  ~ .invalid-feedback {
    display: none;
  }
}


</style>
<div class="content-section" style="margin-top:80px">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card jumbotron">
            <div class="border-bottom mb-4"><h2 style="text-align:center">Create an account</h2></div>
            <article class="card-body">
                {% crispy form %}
                <script>
                        $("#id_branch").change(function () {
                          var branchId = $(this).val();

                          $.ajax({
                            url: "{% url 'accounts:ajax_load_department' %}",
                            data: {
                              'branch': branchId
                            },
                            success: function (data) {
                              $("#id_department").html(data);
                            }
                          });

                        });

                        $(document).ready(function(){
                            $( "#submit-id-submit" ).removeClass( "btn-primary" );
                        });
                </script>
            </article>

            <div class="border-top pt-3" style="text-align:center">
                <small class="text-muted">Have an account? <a class="ml-2" href="{% url 'accounts:login' %}">Login</a></small>
            </div>
</div>
</div>
 </div>
</div>

{% endblock content %}