Source/eDCMS/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path('login/', views.mylogin, name='login'),
    path('', views.home, name='home'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('signup', views.signup, name='signup'),
    path('reset-password/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', views.profile, name='profile_page'),
    path('profile_update/', views.update_profile, name='profile_update'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
    path('ajax/load-department/', views.load_department, name='ajax_load_department'),
    path('home/dashboard/', views.DashboardView.as_view(), name='dashboard'),
]

Source/eDCMS/eDCMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('recordmgnts/', include('recordmgnts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('mailings/', include('mailings.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Source/eDCMS/recordmgnts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'recordmgnts'


urlpatterns = [
    path('records/', views.showContainer, name='records'),
    path('records/new_container', views.addContainer, name='new_container'),
    path('records/new_container/success_added', TemplateView.as_view(template_name="success_added.html"), name='success'),
    path('<int:id>/', views.ContainerDetailView.as_view(), name='container_view'),
    path('delete/<int:id>/', views.containerDelete, name='container_delete'),
    path('search/', views.SearchContainerView.as_view(), name='container_search'),
    path('records/edit_records/<int:pk>/', views.containerUpdate, name='edit_records'),
    path('transaction/', views.transaction_log, name='transaction_log'),
    path('load_document_series/', views.load_series_number, name='ajax_load_doc_number'),
    path('ajax/load-locations/', views.load_locations, name='ajax_load_locations'),
    path('ajax/load-containers/', views.load_containers, name='ajax_load_containers'),
    path('transaction/history/', views.transaction_history_view, name='order_transaction_history_view'),
    path('transaction/history/<int:id>/', views.transaction_form_view, name='order_transaction_details_view'),
]

Source/eDCMS/recordmgnts/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from datetime import *
from ckeditor_uploader.fields import RichTextUploadingField


class Container(models.Model):
    class Meta:
        verbose_name_plural     = 'Containers'
    container_serial_number     = models.CharField(max_length=35, unique=True)
    container_description       = RichTextUploadingField()
    status                      = models.BooleanField(default=True)
    created_by                  = models.CharField(max_length=120)
    created_date                = models.DateTimeField(default=datetime.now, blank=True)
    modify_by                   = models.CharField(max_length=120)
    modify_date                 = models.DateTimeField(default=datetime.now, blank=True)
    warehouse                   = models.ForeignKey('generals.Warehouse', on_delete=models.CASCADE)
    bay                         = models.ForeignKey('generals.Bay', on_delete=models.CASCADE)
    row                         = models.CharField(max_length=10, null=True)
    column                      = models.CharField(max_length=10, null=True)
    department                  = models.CharField(max_length=55, null=True)
    history = HistoricalRecords(table_name='container_history')
    is_deleted                  = models.BooleanField(default=False, null=True)

    def __str__(self):
        return self.container_serial_number


class OrderHeader(models.Model):
    class Meta:
        verbose_name_plural     = 'Order Headers'
    doc_type                    = models.ForeignKey('generals.DocumentType', on_delete=models.CASCADE)
    doc_serial_number           = models.CharField(max_length=20, unique=True)
    created_by                  = models.CharField(max_length=120)
    department                  = models.CharField(max_length=55)
    branch                      = models.CharField(max_length=50)
    created_date                = models.DateTimeField(default=datetime.now, blank=True)


class OrderDetail(models.Model):
    class Meta:
        verbose_name_plural     = 'Order Details'
    header                   = models.ForeignKey(OrderHeader, on_delete=models.CASCADE)
    container                = models.ForeignKey(Container, on_delete=models.SET_NULL, null=True)
    barcode                  = models.CharField(max_length=35, null=True)


class ContainerInstance(models.Model):
    class Meta:
        verbose_name            = 'Transaction'
        verbose_name_plural     = 'Transactions'
    container = models.ForeignKey(Container, on_delete=models.SET_NULL, null=True)
    due_date  = models.DateField(null=True)
    user      = models.ForeignKey('accounts.Profile', on_delete=models.CASCADE)
    status    = models.BooleanField(null=True)
    email_sent = models.BooleanField(default=False, null=True)

    @property
    def is_overdue(self):
        if date.today() > self.due_date:
            return True
        return False
        
    def is_returned(self):
        if self.status is True:
            return 'Returned'
        else:
            return 'Not returned'
            
    is_returned.short_description = 'Status'

Source/eDCMS/recordmgnts/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse, reverse
from .models import Container, OrderHeader, OrderDetail, ContainerInstance
from django.contrib.auth.decorators import login_required
from .forms import ContainerForm, ContainerTransactionForm, RequiredFormSet, OrderDetailForm, TransactionFormView, ContainerUpdateForm
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Q
from django.utils import timezone
from django.forms import modelformset_factory
from generals.models import DocumentType, Bay
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import *
from dateutil.relativedelta import relativedelta
from pprint import pprint
import sys
from subprocess import run, PIPE


@login_required
def showContainer(request):

    allContainer = Container.objects.filter(department=request.user.department.department, is_deleted=False)
    paginator = Paginator(allContainer, 5)  # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        query_sets = paginator.page(page)
    except PageNotAnInteger:
        query_sets = paginator.page(1)
    except EmptyPage:
        query_sets = paginator.page(paginator.num_pages)
    context = {'allContainer': query_sets}
    return render(request, 'recordmgnts/records.html', context)


def showHeader(request):

    allHeader = OrderHeader.objects.all()
    context = {'allHeader': allHeader}
    return render(request, 'recordmgnts/transaction_log.html', context)


def showDetail(request):

    allDetail = OrderDetail.objects.all()
    context = {'allDetail': allDetail}
    return render(request, 'recordmgnts/transaction_log.html', context)


def addContainer(request):
    if request.method == 'POST':
        form = ContainerForm(request.POST)
        if form.is_valid():
            container = form.save(commit=False)
            container.created_by = str(request.user)
            container.modify_by = str(request.user)
            container.department = request.user.department.department
            container.save()
            return render(request, 'recordmgnts/success_added.html')
        else:
            messages.error(request, 'Adding unsuccessful')
    else:
        form = ContainerForm()
    return render(request, 'recordmgnts/new_container.html', {'form': form})


def load_locations(request):
    warehouse_id = request.GET.get('warehouse')
    bays = Bay.objects.filter(warehouse=warehouse_id)
    return render(request, 'recordmgnts/location_dropdown.html', {'bays': bays})


class ContainerDetailView(LoginRequiredMixin, DetailView):
    template_name = 'recordmgnts/records_detail.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Container, id=id_, is_deleted=False)


@login_required
def containerDelete(request,id):
    container = Container.objects.get(pk=id)
    if container.status is not True:
        messages.warning(request, 'Unable to delete checked out containers')
        return redirect('recordmgnts:records')

    container.is_deleted = True
    container.save()
    messages.success(request, f'Record has been deleted')
    return redirect('recordmgnts:records')


class SearchContainerView(LoginRequiredMixin, ListView):
    model = Container
    template_name = 'recordmgnts/search_container_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Container.objects.filter(
            Q(container_serial_number__icontains=query) & Q(department=self.request.user.department.department) & Q(is_deleted=False) |
            Q(container_description__icontains=query) & Q(department=self.request.user.department.department) & Q(is_deleted=False)
        )
        return object_list

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(SearchContainerView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


def containerUpdate(request, pk):
    template_name = 'recordmgnts/edit_records.html'
    container = get_object_or_404(Container, pk=pk)

    if container.status is not True:
        messages.warning(request, 'Please check in this container before editing')
        return redirect('recordmgnts:records')

    form = ContainerUpdateForm(request.POST or None, instance=container)
    if form.is_valid():
        container = form.save(commit=False)
        if container.is_deleted is None:
            container.is_deleted = False
        print(container.is_deleted)
        container.modify_date = datetime.now()
        container.modify_by = str(request.user)
        container.save()
        messages.success(request, 'Successfully updated')
        return redirect('recordmgnts:records')

    return render(request, template_name, {'form': form})


@login_required
def transaction_log(request):
    now = date.today()
    initial_header_data = {
        'department': request.user.department,
        'branch': request.user.branch,
        'created_by': request.user,
        'created_date': datetime.now().strftime("%d/%m/%Y, %I:%M %p"),
    }
    DetailFormSet = modelformset_factory(OrderDetail, form=OrderDetailForm, formset=RequiredFormSet, extra=3)
    if request.method == 'POST':
        header_form = ContainerTransactionForm(request.POST)
        detail_form_set = DetailFormSet(request.POST)

        if header_form.is_valid():
            new_header = header_form.save(commit=False)
            new_header.created_date = datetime.now()

            if detail_form_set.is_valid():
                current_doctype = new_header.doc_type
                current_doctype.is_active = False  # set used document type to inactive
                doc_type = new_header.doc_type.document_code[0]
                doc_num = new_header.doc_type.document_code[1:]
                #  create a new doctype with new doc_code
                create_new_doctype(doc_type, doc_num)
                current_doctype.save()
                new_header.save()
                instances = detail_form_set.save(commit=False)
                for instance in instances:
                    create_container_instance(doc_type, instance.container, request.user, new_header.created_date)
                    instance.header = new_header
                    q = Container.objects.get(pk=instance.container.id)
                    instance.barcode = q.container_serial_number
                    if doc_type is 'O':
                        q.status = False
                        q.is_deleted = False
                    elif doc_type is 'I':
                        q.status = True
                        q.is_deleted = False
                    q.save()
                    instance.save()
                messages.success(request, 'Transaction made successfully')
                detail_form_set = DetailFormSet(queryset=OrderDetail.objects.none())
            elif detail_form_set.is_valid() is False:
                header_form = ContainerTransactionForm(initial=initial_header_data)
    else:
        header_form = ContainerTransactionForm(initial=initial_header_data)
        detail_form_set = DetailFormSet(queryset=OrderDetail.objects.none())

    return render(request, 'recordmgnts/container_transaction.html', {'header_form': header_form, 'detail_form': detail_form_set})


def load_series_number(request):
    document_id = request.GET.get('doc_id')
    document_series_number = DocumentType.objects.get(pk=document_id)
    return HttpResponse(document_series_number.document_code)


# def create_new_doc_series_number(doc_series_number):  # create a new SeriesNumber and returns the instance of it
#     new_series_code = str("%04d" % doc_series_number.next_number)
#     new_next_number = doc_series_number.next_number + 1
#     new_doc_series_number = SeriesNumber(series_code=new_series_code, next_number=new_next_number, is_active=True)
#     new_doc_series_number.save()
#     return new_doc_series_number  # return an instance of the newly created SeriesNumber


def create_new_doctype(doctype, counter): #  new_doc_series_number): # create a new doctype when the current doctype is used
    if doctype is 'O':  # doctype == 'O' is a check out, doctype is the first letter of the current document_code
        counter = int(counter) + 1
        counter = "%04d" % counter  # returns a 4 digit counter e.g(0001 instead of 1)
        new_doc_code = 'O' + counter  # increments the counter and combine with letter 'O'
        new_doctype = DocumentType(document_code=new_doc_code, document_description="Document Check Out", is_active=True
                                   )
        new_doctype.save()

    if doctype is 'I':  # doctype == 'I' is a check in, doctype is the first letter of the current document_code
        counter = int(counter) + 1
        counter = "%04d" % counter  # returns a 4 digit counter e.g(0001 instead of 1)
        new_doc_code = 'I' + counter  # increments the counter and combine with letter 'O'
        new_doctype = DocumentType(document_code=new_doc_code, document_description="Document Check In", is_active=True
                                   )
        new_doctype.save()


def load_containers(request):
    document = request.GET.get('doc_type')
    warehouse = request.GET.get('warehouse')
    doc_type = document[0]
    if warehouse:
        if doc_type is 'O':
            containers = Container.objects.filter(status=True, department=request.user.department.department,
                                                is_deleted=False, warehouse=warehouse)
        elif doc_type is 'I':
            container_instance = ContainerInstance.objects.values_list('container', flat=True).filter(status=False, user=request.user)

Source/eDCMS/recordmgnts/templates/recordmgnts/Records.html
{% extends 'accounts/base.html' %}
{% block title %}eDCMS-Containers View{% endblock title %}
{% block content %}

<section>
    <div class="container-fluid">
        <div class="row align-items-start">
            <div class="col-sm-6 col-md-8" style="margin-top:25px">
                <div class="search-bar">
                <form method="GET" action="{% url 'recordmgnts:container_search' %}">
                    <div class="input-group">
                        <input type="text" name="q" class="col-md-4 col-sm-4 form-control" placeholder="Search"/>
                        <span class="input-group-append">
                            <button type="submit" class="btn btn-dark" style="z-index:1"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </form>
                </div>
            </div>
        </div>
    <!---Container table--->
        <div class="row">
            <div class="col align-self-center">
                <button class="btn btn-info" style="float:right;margin-top:30px" onclick="window.location.href='{% url 'recordmgnts:new_container' %}';"><i class="fa fa-pencil"></i>  Add </button>
                <div class="table-responsive">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible text-center col-md-4" role="alert" style="margin:15px auto">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <small class="text-muted">{{ message }}</small>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <h3>Container</h3>
                     <table class="table table-hover table-bordered table-condensed">
                        <tr>
                            <th> Container Serial Number </th><th> Container Description </th><th> Status </th>
<!--                            <th> Created by </th><th> Created date </th><th> Modify by </th><th> Modify Date </th>-->
                            <th> Warehouse </th><th> Location ID </th><th> Actions </th>
                        </tr>
                         {% for Container in allContainer %}
                         <div id="delModal" class="modal fade" role="dialog" caller-id="">
                             <div class="modal-dialog">

                                 <!-- Modal content-->
                                 <div class="modal-content">
                                     <div class="modal-header">
                                         <h4 class="modal-title">Delete</h4>
                                         <button type="button" class="close" data-dismiss="modal">&times;</button>
                                     </div>
                                     <div class="modal-body">
                                         <p>Are you sure you want to delete this container?</p>
                                     </div>
                                     <div class="modal-footer">
                                         <button class="btn btn-danger" id="confirmDeleteButtonModal">Delete</button>
                                         <button type="button" class="btn btn" data-dismiss="modal">Cancel</button>
                                     </div>
                                 </div>

                             </div>
                         </div>
                         <tr>
                             <td>{{ Container.container_serial_number }}</td><td>{% autoescape off %}{{ Container.container_description }}{% endautoescape %}</td><td>{{ Container.status|yesno:"In,Out" }}</td><td>{{ Container.warehouse }}</td><td>{{ Container.bay }}-{{ Container.row }}-{{ Container.column }}</td>
                             <td>
                                 <div style="text-align:center" id="table-actions">
                                        <button class="btn btn-info" title="Edit" onclick="window.location.href='{% url 'recordmgnts:edit_records' Container.id %}';"><i class="fa fa-edit"></i></button>
                                     {% if user.is_superuser or user.is_documentcontroller %}
                                        <button href="{% url 'recordmgnts:container_delete' id=Container.id %}" title="Delete" id="{{Container.id}}" class="btn btn-danger confirm-delete" data-toggle="modal" data-target="#delModal"><i class="fa fa-trash"></i></button>
                                     {% endif %}
                                        <button class="btn btn-dark" title="View" onclick="window.location.href='{% url 'recordmgnts:container_view' Container.id %}';"><i class="fa fa-laptop"></i></button>
                                </div>
                             </td>
                         </tr>
                         {% endfor %}
                         <script>
                             $(document).on('click', '.confirm-delete', function () {
                                $("#delModal").attr("caller-id", $(this).attr("id"));
                             });

                             $(document).on('click', '#confirmDeleteButtonModal', function () {
                                var caller = $("#confirmDeleteButtonModal").closest(".modal").attr("caller-id");
                                window.location = $("#".concat(caller)).attr("href");
                              });
                         </script>
                     </table>

                </div>
                    {% if allContainer.has_other_pages %}
                        <nav aria-label="Search result pages">
                          <ul class="pagination justify-content-center" style="margin-top:30px">
                            {% if allContainer.has_previous %}
                              <li class="page-item"><a class="page-link" href="?page={{ allContainer.previous_page_number }}">Previous</a></li>
                            {% else %}
                              <li class="page-item disabled"><a class="page-link" tabindex="-1" aria-disabled="true">Previous</a></li>
                            {% endif %}
                            {% for i in allContainer.paginator.page_range %}
                              {% if allContainer.number == i %}
                                <li class="page-item active"><a class="page-link">{{ i }} <span class="sr-only">(current)</span></a></li>
                              {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                              {% endif %}
                            {% endfor %}
                            {% if allContainer.has_next %}
                              <li class="page-item"><a class="page-link" href="?page={{ allContainer.next_page_number }}">Next</a></li>
                            {% else %}
                              <li class="page-item disabled"><a class="page-link" tabindex="-1" aria-disabled="true">Next</a></li>
                            {% endif %}
                          </ul>
                        </nav>
                    {% endif %}
            </div>
        </div>
    </div>
</section>




{% endblock content %}

Source/eDCMS/recordmgnts/templates/recordmgnts/container_transaction.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %}eDCMS-Transaction Log{% endblock title %}
{% block content %}
{% spaceless %}
<div class="container" style="margin-top:30px;">
    <div class="col-md-5" style="margin:auto;">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <small class="text-muted">{{ message }}</small>
    </div>
    {% endfor %}
    {% endif %}
    </div>
    <form method="POST" id="orderHeaderForm" data-docnum-url="{% url 'recordmgnts:ajax_load_doc_number' %}">
                <h3>Header</h3>
                <hr>
            {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
            <div class="form-group">
                {{ header_form.doc_type | as_crispy_field }}
                {{ header_form.doc_serial_number | as_crispy_field }}
                {{ header_form.created_by | as_crispy_field }}
                {{ header_form.warehouse| as_crispy_field }}
            </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    {{ header_form.branch | as_crispy_field }}
                    {{ header_form.department | as_crispy_field }}
                    {{ header_form.created_date | as_crispy_field }}
                </div>
            </div>
        </div>
        <br>
        <header>
            <h3>Details</h3>
        </header>
            {{ detail_form.management_form }}
            <a class="add-form-row" style="float:right; margin-top:-15px;" href="">+Add containers</a>
            <hr>
            <div class="form-group">
                {% for form in detail_form %}
                {% for field in form.visible_fields %}
                {% if form.is_bound %}
                {% if field.errors %}
                <div class="form-group form-rows">
                    <b>{{ field.label_tag }}</b>
                    {% render_field field class="form-control is-invalid container-select" %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
                </div>
                {% endfor %}
                {% else %}
                <div class="form-group form-rows">
                    <b>{{ field.label_tag }}</b>
                    {% render_field field class="form-control container-select" %}
                </div>
                {% endif %}
                {% else %}
                <div class="form-group form-rows">
                    <b>{{ field.label_tag }}</b>
                    {% render_field field class="form-control container-select" %}
                </div>
                {% endif %}
                {% endfor %}
                {% endfor %}
            </div>
        <button type="submit" class="btn btn-success col-md-3">Submit</button>
    </form>
</div>


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
    $("#id_doc_type").change(function () {
      var url = $("#orderHeaderForm").attr("data-docnum-url");  // get the url of the `load_series_number` view
      var documentId = $(this).val();  // get the selected documentType ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request
        data: {
          'doc_id': documentId       // add the documentType id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_series_number` view function
          $("#id_doc_serial_number").attr("value",data);  // add attribute value to the input with id #id_doc_serial_number
          get_container(data);
        }
      });

    });
	
	$(document).ready(function(){
		$(".container-select option").hide();
	});

    var counter = 1;

    $(".container-select").change(function(){
        var unique_class = 'option_' + $(this).attr('id');
        var selected_option = $(this).val();
        $(this).addClass("selected");
        $(".container-select option[value=" + selected_option + "]").attr('class', unique_class);
        $(".container-select option[value=" + selected_option + "]").hide();

        $(".selected").click(function(){
            var unique_class = 'option_' + $(this).attr('id');
<!--            var previous_option = $(this).children("." + unique_class).val();-->
            $("." + unique_class).removeAttr("style");
<!--            $(".container-select option[value=" + previous_option + "]").show();-->
            $("." + unique_class).removeAttr('class');
<!--            $(".selected-option-1").removeAttr("style");-->
            var new_option = $(this).val();
<!--            $(this).children("option:selected").addClass("selected-option");-->
            $(".container-select option[value=" + new_option + "]").attr('class', unique_class);
            $(".container-select option[value=" + new_option + "]").hide();
        });
    })

    $("#id_warehouse").click(function(){
        data = $("#id_doc_serial_number").val();
        get_container(data)
    });

    function get_container(data) {
      var form_num = $("#id_form-TOTAL_FORMS").val();
      var forms_arr = [];
      var warehouse = $("#id_warehouse").val();

      for (var i = 0; i < form_num; i++){
        forms_arr[i] = '#id_form-' + i.toString() + '-container';
       }

      $.ajax({
        url: "{% url 'recordmgnts:ajax_load_containers' %}",
        data: {
          'doc_type': data,
          'form_num': form_num,
          'warehouse': warehouse,
        },
        success: function(data){
          for (var i = 0; i < form_num; i++){
            $(forms_arr[i]).html(data)
          }
        }
      });

    };

    function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + prefix + '-TOTAL_FORMS').val(); //initial total number of forms displayed
    newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() { //set the name and id for each new input addded
        var name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('');
    });
    newElement.find('label').each(function() { //set label for each new input added
        var forValue = $(this).attr('for');
        if (forValue) {
          forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
          $(this).attr({'for': forValue});
        }
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total); //set total number of forms displayed to hidden input id_form-TOTAL_FORMS variable
    $(selector).after(newElement)
    return false;
}

    $(document).on('click', '.add-form-row', function(e){
    e.preventDefault();
    cloneMore('.form-rows:last', 'form'); // .form-row:last selects the last form-row class
    return false;
});

  </script>
{% endspaceless %}
{% endblock content %}

Source/eDCMS/recordmgnts/templates/recordmgnts/success_added.html
{% extends 'accounts/base.html' %}
{% block content %}
<div class ="container" style="margin-top:30px">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'recordmgnts:records' %}">Records</a></li>
        <li class="breadcrumb-item"><a href="{% url 'recordmgnts:new_container' %}">New container</a></li>
        <li class="breadcrumb-item active">Added</li>
    </ol>
</div>
<div class="container">
    <h1>Added successfully!</h1><br>
    <h4 style="margin-bottom:25px;">You have added new container.</h4>
    <button type="button" class="btn btn-secondary" onclick="window.location.href='{% url 'recordmgnts:records' %}';" style="margin-bottom:5px">Return to records</button>
    <button type="button" class="btn btn-secondary" onclick="window.location.href='{% url 'recordmgnts:new_container' %}';" style="margin-bottom:5px">Add another record</button>
</div>

{% endblock content %}